export const DAILY_QUIZ_TOPICS = [
  "General Knowledge",
  "World Geography",
  "Pop Culture of the 2010s",
  "History of Ancient Civilizations",
  "Basic Astronomy",
  "Famous Scientists and Inventors",
  "Classic Literature",
  "Movies of the 90s",
  "Human Anatomy",
  "Technology and Internet History",
  "Wildlife and Animals",
  "Capital Cities of the World",
  "Famous Landmarks",
  "Food and Cuisine Around the World",
  "Musical Instruments",
  "The Human Brain",
  "Video Game History",
  "Mythology from Around the World",
  "Modern Architecture",
  "Space Exploration",
];
